"""Add average_duration_minutes to services

Revision ID: 1a137ed244c2
Revises: 3766b3db3744
Create Date: 2026-01-25 10:58:56.175741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a137ed244c2'
down_revision: Union[str, None] = '3766b3db3744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('average_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'average_duration_minutes')
    # ### end Alembic commands ###
