"""Add daily reconciliation table

Revision ID: 3766b3db3744
Revises: 44b46a5b7b01
Create Date: 2026-01-25 09:38:14.045965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3766b3db3744'
down_revision: Union[str, None] = '44b46a5b7b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reconciliations',
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('expected_cash', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Integer(), nullable=False),
    sa.Column('total_bills', sa.Integer(), nullable=False),
    sa.Column('actual_cash', sa.Integer(), nullable=True),
    sa.Column('cash_difference', sa.Integer(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciled_by', sa.String(length=26), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reconciliations_reconciliation_date'), 'daily_reconciliations', ['reconciliation_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_reconciliations_reconciliation_date'), table_name='daily_reconciliations')
    op.drop_table('daily_reconciliations')
    # ### end Alembic commands ###
