"""Add daily goals to salon settings

Revision ID: 41d2148c77a2
Revises: f7g8h9i0j1k2
Create Date: 2026-02-07 11:30:46.654556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41d2148c77a2'
down_revision: Union[str, None] = 'f7g8h9i0j1k2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed incorrect table drop operations for pending_payment_collections
    # The table should remain as it's a required feature
    op.alter_column('appointments', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_customers_phone', table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.add_column('salon_settings', sa.Column('daily_revenue_target_paise', sa.Integer(), nullable=False, server_default='2000000'))
    op.add_column('salon_settings', sa.Column('daily_services_target', sa.Integer(), nullable=False, server_default='25'))

    # Backfill existing rows with default values (server_default only affects new rows)
    op.execute("""
        UPDATE salon_settings
        SET daily_revenue_target_paise = 2000000,
            daily_services_target = 25
        WHERE daily_revenue_target_paise IS NULL
           OR daily_services_target IS NULL
    """)

    op.alter_column('walkins', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed incorrect table creation operations for pending_payment_collections
    # The table already exists from a previous migration
    op.alter_column('walkins', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('salon_settings', 'daily_services_target')
    op.drop_column('salon_settings', 'daily_revenue_target_paise')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
