"""Add cancellation fields to walkins

Revision ID: 44b46a5b7b01
Revises: 01d5c8e3f4a1
Create Date: 2026-01-25 03:52:27.582338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b46a5b7b01'
down_revision: Union[str, None] = '01d5c8e3f4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walkins', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('walkins', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walkins', 'cancellation_reason')
    op.drop_column('walkins', 'cancelled_at')
    # ### end Alembic commands ###
