"""Add session_id, bill_id, and checked_in_at to walkins

Revision ID: 5f22b2a9d812
Revises: 890347448c6e
Create Date: 2026-01-22 15:39:11.438721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f22b2a9d812'
down_revision: Union[str, None] = '890347448c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walkins', sa.Column('session_id', sa.String(length=26), nullable=True))
    op.add_column('walkins', sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('walkins', sa.Column('bill_id', sa.String(length=26), nullable=True))
    op.create_index(op.f('ix_walkins_bill_id'), 'walkins', ['bill_id'], unique=False)
    op.create_index(op.f('ix_walkins_session_id'), 'walkins', ['session_id'], unique=False)
    op.create_index(op.f('ix_walkins_status'), 'walkins', ['status'], unique=False)
    op.create_foreign_key(None, 'walkins', 'bills', ['bill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'walkins', type_='foreignkey')
    op.drop_index(op.f('ix_walkins_status'), table_name='walkins')
    op.drop_index(op.f('ix_walkins_session_id'), table_name='walkins')
    op.drop_index(op.f('ix_walkins_bill_id'), table_name='walkins')
    op.drop_column('walkins', 'bill_id')
    op.drop_column('walkins', 'checked_in_at')
    op.drop_column('walkins', 'session_id')
    # ### end Alembic commands ###
