"""make invoice_number nullable

Revision ID: 5f8f6222177c
Revises: 5f22b2a9d812
Create Date: 2026-01-24 09:05:12.954360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8f6222177c'
down_revision: Union[str, None] = '5f22b2a9d812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
