"""make_appointment_phone_nullable

Revision ID: e0c1c3273fbb
Revises: f27fc6b8b70f
Create Date: 2026-02-02 19:12:30.364898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c1c3273fbb'
down_revision: Union[str, None] = 'f27fc6b8b70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('walkins', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('walkins', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
