"""Pydantic schemas for accounting reports and dashboards."""

from datetime import date, datetime
from typing import Optional, List, Dict
from pydantic import BaseModel, Field, ConfigDict


# ============ Dashboard Schemas ============

class DashboardMetrics(BaseModel):
    """Real-time dashboard metrics for current day."""

    # Today's date
    today: date = Field(..., description="Current date (IST)")

    # Real-time counts
    total_bills: int = Field(..., description="Number of bills created today")
    completed_appointments: int = Field(..., description="Appointments completed today")
    active_appointments: int = Field(..., description="Currently in-progress appointments")
    pending_appointments: int = Field(..., description="Scheduled for today, not started")

    # Revenue metrics (in paise)
    gross_revenue: int = Field(..., description="Total revenue before discounts (paise)")
    discount_amount: int = Field(..., description="Total discounts given (paise)")
    net_revenue: int = Field(..., description="Revenue after discounts (paise)")

    # Tax breakdown (in paise)
    cgst_collected: int = Field(..., description="CGST collected (paise)")
    sgst_collected: int = Field(..., description="SGST collected (paise)")
    total_tax: int = Field(..., description="Total tax collected (paise)")

    # Payment split (in paise)
    cash_collected: int = Field(..., description="Cash payments (paise)")
    digital_collected: int = Field(..., description="Digital payments (paise)")

    # Cash drawer status
    cash_drawer_open: bool = Field(..., description="Is cash drawer currently open")
    cash_drawer_opening_float: Optional[int] = Field(None, description="Opening float if drawer open (paise)")
    cash_drawer_expected_cash: Optional[int] = Field(None, description="Expected cash in drawer (paise)")

    # Rupee convenience properties
    @property
    def gross_revenue_rupees(self) -> float:
        """Gross revenue in rupees."""
        return self.gross_revenue / 100.0

    @property
    def net_revenue_rupees(self) -> float:
        """Net revenue in rupees."""
        return self.net_revenue / 100.0


class ServicePerformance(BaseModel):
    """Performance metrics for a specific service."""
    service_id: str
    service_name: str
    count: int = Field(..., description="Number of times service was performed")
    total_revenue: int = Field(..., description="Total revenue from this service (paise)")

    @property
    def total_revenue_rupees(self) -> float:
        """Total revenue in rupees."""
        return self.total_revenue / 100.0


class StaffPerformance(BaseModel):
    """Performance metrics for a staff member."""
    staff_id: str
    staff_name: str
    services_completed: int = Field(..., description="Number of services completed")
    total_revenue: int = Field(..., description="Revenue generated by this staff (paise)")

    @property
    def total_revenue_rupees(self) -> float:
        """Total revenue in rupees."""
        return self.total_revenue / 100.0


class DashboardResponse(BaseModel):
    """Complete dashboard with metrics and performance data."""
    metrics: DashboardMetrics
    top_services: List[ServicePerformance] = Field(default_factory=list, description="Top 5 performing services")
    staff_performance: List[StaffPerformance] = Field(default_factory=list, description="Staff performance today")


# ============ Day Summary Schemas ============

class DaySummaryResponse(BaseModel):
    """Daily business summary."""
    id: str
    summary_date: date

    # Bill counts
    total_bills: int
    refund_count: int

    # Revenue (paise)
    gross_revenue: int
    discount_amount: int
    refund_amount: int
    net_revenue: int

    # Tax breakdown (paise)
    cgst_collected: int
    sgst_collected: int
    total_tax: int

    # Payment split (paise)
    cash_collected: int
    digital_collected: int

    # COGS and profit (owner only)
    estimated_cogs: int
    estimated_profit: int

    # Metadata
    generated_at: datetime
    generated_by: Optional[str]
    is_final: bool

    model_config = ConfigDict(from_attributes=True)

    @property
    def net_revenue_rupees(self) -> float:
        """Net revenue in rupees."""
        return self.net_revenue / 100.0

    @property
    def estimated_profit_rupees(self) -> float:
        """Estimated profit in rupees."""
        return self.estimated_profit / 100.0


class DaySummaryListResponse(BaseModel):
    """Paginated list of daily summaries."""
    items: List[DaySummaryResponse]
    total: int
    page: int
    size: int
    pages: int


# ============ Monthly Report Schemas ============

class MonthlyReportResponse(BaseModel):
    """Monthly aggregated report."""
    month: str = Field(..., description="Month in YYYY-MM format")
    year: int
    month_number: int

    # Aggregated counts
    total_bills: int
    total_refunds: int
    business_days: int = Field(..., description="Number of days with transactions")

    # Revenue totals (paise)
    gross_revenue: int
    discount_amount: int
    refund_amount: int
    net_revenue: int

    # Tax totals (paise)
    cgst_collected: int
    sgst_collected: int
    total_tax: int

    # Payment split (paise)
    cash_collected: int
    digital_collected: int

    # COGS and profit (owner only)
    estimated_cogs: int
    estimated_profit: int

    # Daily breakdown
    daily_summaries: List[DaySummaryResponse] = Field(default_factory=list)

    @property
    def net_revenue_rupees(self) -> float:
        """Net revenue in rupees."""
        return self.net_revenue / 100.0

    @property
    def estimated_profit_rupees(self) -> float:
        """Estimated profit in rupees."""
        return self.estimated_profit / 100.0


# ============ Tax Report Schemas ============

class TaxReportEntry(BaseModel):
    """Single entry in tax report."""
    date: date
    bill_count: int
    taxable_amount: int = Field(..., description="Amount before tax (paise)")
    cgst_amount: int = Field(..., description="CGST collected (paise)")
    sgst_amount: int = Field(..., description="SGST collected (paise)")
    total_tax: int = Field(..., description="Total tax (paise)")
    gross_amount: int = Field(..., description="Amount including tax (paise)")

    @property
    def taxable_amount_rupees(self) -> float:
        """Taxable amount in rupees."""
        return self.taxable_amount / 100.0

    @property
    def total_tax_rupees(self) -> float:
        """Total tax in rupees."""
        return self.total_tax / 100.0


class TaxReportResponse(BaseModel):
    """GST tax report for compliance."""
    period_start: date
    period_end: date
    gstin: Optional[str] = Field(None, description="Business GSTIN")
    salon_name: str
    salon_address: str

    # Summary totals (paise)
    total_bills: int
    total_taxable_amount: int
    total_cgst: int
    total_sgst: int
    total_tax: int
    total_gross_amount: int

    # Detailed breakdown
    entries: List[TaxReportEntry] = Field(default_factory=list)

    # Generation metadata
    generated_at: datetime
    generated_by: str

    @property
    def total_tax_rupees(self) -> float:
        """Total tax in rupees."""
        return self.total_tax / 100.0


# ============ Profit & Loss Schemas ============

class PLRevenue(BaseModel):
    """Revenue breakdown for P&L statement."""
    gross_revenue: int = Field(..., description="Total revenue before discounts (paise)")
    discount_amount: int = Field(..., description="Total discounts (paise)")
    refund_amount: int = Field(..., description="Total refunds (paise)")
    net_revenue: int = Field(..., description="Revenue after discounts and refunds (paise)")

    @property
    def net_revenue_rupees(self) -> float:
        return self.net_revenue / 100.0


class PLCostOfGoodsSold(BaseModel):
    """COGS breakdown for P&L statement."""
    service_cogs: int = Field(..., description="Cost of materials used for services (paise)")
    product_cogs: int = Field(..., description="Cost of retail products sold (paise)")
    total_cogs: int = Field(..., description="Total COGS (paise)")

    @property
    def total_cogs_rupees(self) -> float:
        return self.total_cogs / 100.0


class PLOperatingExpenses(BaseModel):
    """Operating expenses breakdown by category."""
    by_category: Dict[str, int] = Field(default_factory=dict, description="Expenses by category (paise)")
    total_expenses: int = Field(..., description="Total operating expenses (paise)")

    @property
    def total_expenses_rupees(self) -> float:
        return self.total_expenses / 100.0


class PLProfitability(BaseModel):
    """Profitability metrics for P&L statement."""
    gross_profit: int = Field(..., description="Revenue - COGS (paise)")
    net_profit: int = Field(..., description="Gross profit - Operating expenses (paise)")
    gross_margin_percent: float = Field(..., description="Gross profit / Revenue * 100")
    net_margin_percent: float = Field(..., description="Net profit / Revenue * 100")

    @property
    def gross_profit_rupees(self) -> float:
        return self.gross_profit / 100.0

    @property
    def net_profit_rupees(self) -> float:
        return self.net_profit / 100.0


class ProfitLossResponse(BaseModel):
    """Detailed Profit & Loss statement."""
    period_start: date
    period_end: date

    # Revenue
    revenue: PLRevenue

    # Cost of Goods Sold
    cogs: PLCostOfGoodsSold

    # Operating Expenses
    operating_expenses: PLOperatingExpenses

    # Profitability
    profitability: PLProfitability

    # Additional metrics
    total_bills: int = Field(..., description="Number of bills in period")
    tips_collected: int = Field(0, description="Total tips (paise)")

    # Generation metadata
    generated_at: datetime


# ============ Filter/Query Schemas ============

class ReportFilters(BaseModel):
    """Query parameters for filtering reports."""
    start_date: Optional[str] = Field(None, description="Start date (YYYY-MM-DD)")
    end_date: Optional[str] = Field(None, description="End date (YYYY-MM-DD)")
    month: Optional[str] = Field(None, description="Month (YYYY-MM)")
    year: Optional[int] = Field(None, description="Year (YYYY)")
    page: int = Field(1, ge=1)
    size: int = Field(20, ge=1, le=100)


# ============ Export Schemas ============

class ExportRequest(BaseModel):
    """Request to export a report."""
    export_type: str = Field(..., description="Type of export (daily_summary, monthly, tax)")
    export_format: str = Field(..., description="Format (pdf, xlsx, csv)")
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    month: Optional[str] = None  # YYYY-MM format


class ExportResponse(BaseModel):
    """Response after export generation."""
    export_id: str
    export_type: str
    export_format: str
    file_path: str
    file_size: int
    parameters: Dict
    exported_at: datetime
    exported_by: str

    # Download URL (will be implemented later)
    download_url: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)
